add Pathauto to site
Pronovix/food pull request #20
Opened 2020-03-25 12:38 UTC by mariaburany

2020-03-25 19:02 UTC, gkurucz requested changes

2020-03-25 19:02 UTC, gkurucz commented on config/sync/system.performance.yml
> +  preprocess: false
Same issue as here: https://github.com/Pronovix/food/pull/17#discussion_r398096150

Otherwise it looks good :+1:

2020-03-26 06:54 UTC, lekob submitted a review, later dismissed

2020-03-26 07:25 UTC, gkurucz submitted a review, later dismissed

2020-03-26 15:18 UTC, closed without merging