Issue/7957 > master
Pronovix/food pull request #26
Opened 2020-03-31 09:10 UTC by davidgrindmill

Add theming to hero.

2020-03-31 09:19 UTC, gkurucz requested changes

2020-03-31 09:19 UTC, gkurucz commented on config/sync/user.role.authenticated.yml
> -  - 'use text format loggedin_text_filter'
Uh oh, I think you removed the changes from Balazs... :) Did you export your config, pull the latest changes then import the config before pushing your changes?

2020-03-31 09:19 UTC, gkurucz commented on config/sync/core.entity_form_display.node.landing_page.default.yml
>      - field.field.node.landing_page.field_image
Now that you have a hero image field, do you still need the other image field? Shouldn't this be removed?

2020-03-31 19:42 UTC, dzadza approved these changes

2020-03-31 19:42 UTC, dzadza commented on config/sync/core.entity_view_display.node.landing_page.default.yml
> +                  image_style: ''
Don't you want to use the `extra_large` image style here?

2020-03-31 19:43 UTC, dzadza approved these changes

2020-04-01 06:35 UTC, lekob approved these changes

2020-04-01 07:54 UTC, gkurucz approved these changes

2020-04-01 10:00 UTC, merged