Product API
Pronovix/food pull request #43
Opened 2020-04-20 06:52 UTC by BeneBalazs

2020-04-22 09:02 UTC, lekob requested changes

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $nodes = $this->entityTypeManager->getStorage('node')->loadMultiple($ids);
What happens if there aren't any nodes?

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +  use StringTranslationTrait;
StringTranslationTrait is used by ControllerBase. You don't need to use it again.

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    if ($salutation == $this->t('Good Morning')) {
Use the identical comparison operator (===).

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    elseif ($salutation == $this->t('Good Afternoon')) {
Use the identical comparison operator (===).

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $ids = $query->condition('type', 'article')
What happens if there aren't any articles fitting the conditions?

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +      $container->get('usergreeting.greeting')
This module depends on the `usergreeting` module, but it does not list it in its dependencies.

2020-04-22 09:02 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +  public function getTaxonomy(): string {
This method returns a string, not a Taxonomy. I would expect a Taxonomy from a method called getTaxonomy.

2020-04-27 16:32 UTC, lekob requested changes

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +
Unnecessary empty line.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +use Drupal\Core\Entity\EntityTypeManager;
An entity type manager is provided for you in ControllerBase. Use the entityTypeManager() method instead.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +  protected $entityTypeManager;
An entity type manager is provided for you in ControllerBase. Use the entityTypeManager() method instead.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $this->entityTypeManager = $entity_type_manager;
An entity type manager is provided for you in ControllerBase. Use the entityTypeManager() method instead.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $query = $this->entityTypeManager->getStorage('node')->getQuery();
An entity type manager is provided for you in ControllerBase. Use the entityTypeManager() method instead.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +      $nodes = $this->entityTypeManager->getStorage('node')->loadMultiple($ids);
An entity type manager is provided for you in ControllerBase. Use the entityTypeManager() method instead.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    else {
Unnecessary else block.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $greetingtext = $this->greeting->greetingMessage();
You can use ->render() on the TranslatableMarkup object to render it into a string.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $salutation = (string) $greetingtext;
Unnecessary new variable. If you render the TranslatableMarkup you don't need to cast it to a string.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    if ($salutation === (string) $this->t('Good Morning')) {
This is just creating a string with extra steps. This string is used for comparison, it will not be translated.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    elseif ($salutation === (string) $this->t('Good Afternoon')) {
This is just creating a string with extra steps. This string is used for comparison, it will not be translated.

2020-04-27 16:32 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +class RecommendedRecipeController extends ControllerBase {
It is probably a good idea to make this class final.

2020-04-29 11:26 UTC, lekob requested changes

2020-04-29 11:26 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    $greetingtext = render($this->greeting->greetingMessage());
The TranslatableMarkup object has a render() method on it.

2020-04-29 11:26 UTC, lekob commented on web/modules/custom/recommended_recipe/src/Controller/RecommendedRecipeController.php
> +    }
I don't think this is necessary. If the query finds ids the storage will load them.

2020-04-29 12:53 UTC, lekob approved these changes

2020-04-29 12:58 UTC, gkurucz approved these changes

2020-04-29 12:59 UTC, merged