Time of the day - correction (issue/8247)
Pronovix/food pull request #46
Opened 2020-04-22 18:17 UTC by kingfisher88

Remove "anonymous (not verified)" from greeting message for anonymous users.
Change the service that returns the current time of day, returns just the
greeting message according to the time of day.

2020-04-23 07:21 UTC, lekob requested changes

2020-04-23 07:21 UTC, lekob commented on web/modules/custom/usergreeting/src/GreetingTime.php
>    protected $stringTranslation;
The $stringTranslation property is defined in StringTranslationTrait. No need to redefine it here.

2020-04-23 07:21 UTC, lekob commented on web/modules/custom/usergreeting/src/GreetingTime.php
>     * @return string
You are not returning a string.

2020-04-23 07:21 UTC, lekob commented on web/modules/custom/usergreeting/src/GreetingTime.php
>      $config_afternoon = $this->configFactory->get('usergreeting.settings')->get('afernoon_start');
afternoon

2020-04-23 07:21 UTC, lekob commented on web/modules/custom/usergreeting/src/Plugin/Block/UsergreetingBlock.php
>    public function build() {
Declare array return type.

2020-04-23 08:01 UTC, gkurucz commented on web/modules/custom/usergreeting/src/GreetingTime.php
>    protected $stringTranslation;
According to https://api.drupal.org/api/drupal/core!lib!Drupal!Core!StringTranslation!StringTranslationTrait.php/trait/StringTranslationTrait/8.8.x he should.

> If the class is capable of injecting services from the container, it should inject the 'string_translation' service and assign it to $this->stringTranslation.

I've also seen this exact same practice in core.

2020-04-23 11:58 UTC, gkurucz commented on web/modules/custom/usergreeting/src/Plugin/Block/UsergreetingBlock.php
> +    if ($this->account->isAnonymous() === TRUE) {
This condition can be simplified.

```
$message = [
  common_stuff...
];

if (condition) {
  $message['different_stuff'] = 'different_stuff';
}
```

2020-04-24 10:13 UTC, gkurucz approved these changes

2020-04-24 10:14 UTC, lekob approved these changes

2020-04-24 10:27 UTC, merged