create Ingredients Vocab and the Ingredients Term reference field
Pronovix/food pull request #48
Opened 2020-04-27 15:04 UTC by mariaburany

2020-04-27 15:06 UTC, gkurucz submitted a review, later dismissed

2020-04-27 15:57 UTC, lekob requested changes

2020-04-27 15:57 UTC, lekob commented on config/sync/core.entity_form_display.user.user.default.yml
> +    weight: 30
This doesn't look like it is related to the new entity reference field.

2020-04-27 15:57 UTC, lekob commented on config/sync/core.extension.yml
> +  ingredient_term: 0
This module doesn't exist yet. Therefore it cannot be installed.

2020-04-27 15:57 UTC, lekob commented on config/sync/views.view.recipe_list.yml
> +      title: 'Recent Recipes'
This doesn't look like it is related to the new entity reference field.

2020-04-28 06:53 UTC, lekob approved these changes

2020-04-28 07:50 UTC, gkurucz approved these changes

2020-04-28 08:03 UTC, merged